# Generated by Django 3.2.6 on 2022-02-14 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('priority', models.CharField(choices=[('1', 'high'), ('2', 'moderate'), ('3', 'Low')], default=None, max_length=2)),
                ('status', models.CharField(choices=[('1', 'on_progress'), ('2', 'closed')], default=None, max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
