# Generated by Django 3.2.6 on 2022-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
